### ISSUE TITLE
Emitter::emit is not being optimized by the VM

### ISSUE THREAD

**Issue by nathansobo** [atom-archive/emissary#5]
![screenshot 2014-07-28 10 05 41](https://cloud.githubusercontent.com/assets/1789/3723200/22f962be-1671-11e4-98ce-c3f567b0d16d.png)

This is a big deal because this method is used all over the place in our model. This is caused by using an `args...` formal parameter. This [issue](https://github.com/jashkenas/coffeescript/issues/3274) is tracking the problem in CoffeeScript.

@benogle: I remember you mentioning seeing `emit` as a huge part of the profile in find and replace. This seems like it could be a big part of the reason why.

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
